hsp = choose(-2,-1,1,2);
vsp = choose(-2,-1,1,2);
pickedUp = false;
canBePickedUp = false;
pickUpCoolDown = room_speed*0.1;
item = new WoodHatchet();
lifeSpan = room_speed*30;
image_xscale = 0.5;
image_yscale = 0.5;